[32m2024-07-12 02:18:04 +0400[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - 777d71c6-b792-466c-b656-083edca48dd2 - 41091 - LOGS_CAPTURED - Started capturing logs in process (pid: 41091).
[32m2024-07-12 02:18:04 +0400[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - 777d71c6-b792-466c-b656-083edca48dd2 - 41091 - backfill_historical_data - STEP_START - Started execution of step "backfill_historical_data".
[32m2024-07-12 02:18:04 +0400[0m - dagster - [34mERROR[0m - [31m__ephemeral_asset_job__ - 777d71c6-b792-466c-b656-083edca48dd2 - 41091 - backfill_historical_data - STEP_FAILURE - Execution of step "backfill_historical_data" failed.

dagster._core.errors.DagsterInvariantViolationError: Cannot access partition_key for a non-partitioned run

Stack Trace:
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 494, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 198, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 167, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/user/Desktop/ameria/v2/dagster_module/assets.py", line 26, in backfill_historical_data
    partition_date = context.asset_partition_key_for_output()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/decorator_utils.py", line 203, in wrapped_with_pre_call_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/context/compute.py", line 1504, in asset_partition_key_for_output
    return self.op_execution_context.asset_partition_key_for_output(output_name=output_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/context/compute.py", line 729, in asset_partition_key_for_output
    return self._step_execution_context.asset_partition_key_for_output(output_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/context/system.py", line 1107, in asset_partition_key_for_output
    start, end = self.asset_partition_key_range_for_output(output_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/context/system.py", line 1102, in asset_partition_key_range_for_output
    return self.asset_partition_key_range
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/ameria/lib/python3.12/site-packages/dagster/_core/execution/context/system.py", line 427, in asset_partition_key_range
    raise DagsterInvariantViolationError(
[0m
